In [2]:
# prompt: !pip3 install torch
#!pip3 install torch

In [20]:
import torch
torch.__version__

'2.5.1'

## 01. 텐서 초기화
- 초기화 : 텐서에 특정 값을 채워서 생성하는 것

In [4]:
import torch
import numpy as np

# pytorch version확인
torch.__version__

'2.5.1'

### 1-1. 초기화 되지 않은 Tensor
- 특정한 값이 채워지지 않은 상태로 생성하는 것

In [5]:
tensor = torch.empty(4,2)
print(tensor)

tensor([[-1.9542e-03,  9.2486e-43],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


### 1-2. 상수로 초기화된 Tensor
- 'torch.zeros()'
- 'torch.ones()'

In [6]:
a = torch.ones(3,4, dtype = torch.long) # dtype = 데이터타입 지정
b = torch.zeros(2,2)

print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


### 1-3. 무작위하게 초기화된 Tensor
- 'torch.rand' = 0~1사이의 값으로 무작위로 초기화
- 'torch.randn' = 표준정규분포에서 무작위로 초기화

In [22]:
a = torch.rand(3,3)
b = torch.randn(3,3)
print(a)
print(b)

tensor([[0.5602, 0.6685, 0.9309],
        [0.7266, 0.6961, 0.6167],
        [0.6905, 0.9305, 0.2317]])
tensor([[ 0.3060,  0.0562,  0.3205],
        [-0.7044,  0.6527, -0.1166],
        [ 0.2270,  0.0436,  1.8925]])


### 1-4. 직접 입력한 값으로 초기화

In [8]:
a = torch.tensor([1,2.3])
print(a)

tensor([1.0000, 2.3000])


### 1-5. NumPy 배열로부터 초기화

In [9]:
#넘파이를 텐서로
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)

#텐서를 넘파이로
b = torch.tensor([1,2.3,4,5])
new_nd = b.numpy()
new_nd[2] = 100 #얕은 복사임

print(new_nd)
print(b)

[  1.    2.3 100.    5. ]
tensor([  1.0000,   2.3000, 100.0000,   5.0000])


### 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [10]:
a = torch.ones(3,4, dtype = torch.long) # dtype = 데이터타입 지정
b = torch.zeros_like(a,dtype = torch.float) # a에 가져온 크기에 맞춰 아무숫자나 넣어줌
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 1-7. 텐서의 속성

In [11]:
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor = torch.rand(3,4,dtype = torch.float64)
# tensor = tensor.to(device) # gpu로 옮기기

print(tensor.size()) # 사이즈(함수를 이용한것)
print(tensor.shape) # 사이즈
print(tensor.dtype) # 데이터타입
print(tensor.device) # 디바이스


torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cpu


### 1-8. 특정 타입의 텐서 생성

In [12]:
tensor = torch.rand(3,4,dtype = torch.float64)
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.dtype)

int_tensor = torch.IntTensor([1.1,2.2,3.8])
print(int_tensor)
print(int_tensor.dtype)

torch.float32
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


### 1-9. 데이터 타입 캐스팅 (데이터 타입을 변환하는것을 말함)


In [13]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1.1,2.2,3.8])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA Tensor

In [14]:
tensor = torch.rand(3,4,dtype = torch.float64)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #가능하면 쿠다 쓰고 아니면 cpu씀
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

### 1-11. 다차원 텐서 표현

#### 1-11-1. 0D Tensor(Scalr)
- 하나의 값을 담고 있는 텐서

In [15]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


### 1-11-2. 1D Tensor(Vector)
- 값들을 저장하고 있는 리스트와 유사한 텐서(배열형태)

In [16]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 1-11-3. 2D Tensor(Vector)
- 행렬과 같은 모양으로 두개의 축이 존재

In [17]:
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 1-11-4. 3D Tensor(Cube)
- 큐브와 같은 형태로 세 개의 축이 존재

In [18]:
t3 = torch.tensor([[[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]]
                  ])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([4, 3, 2])
tensor([[[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]]])


### 1-11-5. 4D Tensor(Cube)
- 큐브와 같은 형태로 네 개의 축이 존재

In [19]:
t4 = torch.rand(2,3,4,5)
t4

tensor([[[[6.9425e-01, 2.7672e-01, 2.4285e-01, 6.2511e-01, 8.7198e-01],
          [5.7706e-01, 4.2826e-01, 1.7487e-01, 8.5186e-01, 1.1784e-01],
          [2.2730e-01, 2.4367e-01, 4.4098e-01, 5.3804e-01, 2.3502e-01],
          [5.4874e-02, 9.4427e-01, 7.8201e-01, 3.8484e-01, 7.9443e-01]],

         [[8.7931e-01, 3.4106e-01, 2.6053e-01, 1.3790e-01, 2.5918e-01],
          [5.9871e-01, 7.2092e-01, 8.5111e-01, 1.1038e-01, 6.2164e-01],
          [5.7550e-01, 3.5856e-01, 9.8333e-01, 8.1529e-01, 7.9434e-01],
          [8.2112e-02, 5.5684e-01, 5.3260e-01, 2.0680e-01, 4.7136e-01]],

         [[2.3832e-01, 2.4270e-01, 6.5034e-01, 5.6555e-01, 6.9703e-01],
          [5.4349e-01, 9.7030e-01, 6.9102e-02, 4.6625e-02, 6.8385e-01],
          [7.6686e-01, 3.3701e-02, 2.4695e-01, 9.9535e-01, 6.2857e-01],
          [1.3560e-01, 7.5621e-01, 3.3886e-01, 5.7932e-02, 2.9974e-01]]],


        [[[3.3941e-01, 2.0214e-02, 1.6398e-01, 6.5642e-01, 6.7515e-01],
          [2.0235e-01, 2.2560e-04, 6.2276e-01, 5.0535e-0