## 02. 텐서의 연산

In [1]:
import torch

### 2-1. 산술 연산

In [18]:
tensor = torch.rand(2,2)
print(tensor)

tensor = tensor * 2
print(tensor)

tensor = tensor + 1
print(tensor)



tensor([[0.4845, 0.1688],
        [0.0951, 0.0998]])
tensor([[0.9690, 0.3376],
        [0.1902, 0.1995]])
tensor([[1.9690, 1.3376],
        [1.1902, 1.1995]])


In [27]:
# 여러개의 텐서를 연산
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y) 

# print(x)
# print(y)
# print(x+y)
# print(add)
print(x,y)

# in-place 바꿔치기 연산
add = torch.add(x,y)
print(add)
y.add_(x) #앞에있는 값에 덮어 씌움
print(y)

tensor([[0.2336, 0.0515],
        [0.2707, 0.3133]]) tensor([[0.8622, 0.3658],
        [0.8913, 0.0134]])
tensor([[1.0958, 0.4172],
        [1.1621, 0.3268]])
tensor([[1.0958, 0.4172],
        [1.1621, 0.3268]])


In [33]:
# 빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x-y)
print(sub) 

tensor([[ 0.0059,  0.5050],
        [ 0.6340, -0.2019]])
tensor([[ 0.0059,  0.5050],
        [ 0.6340, -0.2019]])


In [35]:
# 곱하기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x*y)
print(mul) 

tensor([[0.0437, 0.1617],
        [0.1624, 0.2783]])
tensor([[0.0437, 0.1617],
        [0.1624, 0.2783]])


In [37]:
# 나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x,y)
print(x/y)
print(div) 

tensor([[1.0163, 1.2845],
        [3.8754, 2.0435]])
tensor([[1.0163, 1.2845],
        [3.8754, 2.0435]])


### 2-2. 각종연산

In [19]:
a = torch.tensor(-10)
print("절대값 :", torch.abs(a))

b = torch.tensor(4.5)
print("올림 :", torch.ceil(b))
print("반올림 :", torch.round(b))
print("내림 :", torch.floor(b))

c = torch.tensor([[0.8,0.3],[-0.9,0.4]])
print("클램프",torch.clamp(c, -0.5,0.5)) #최솟값,최댓값을 정하고 이 값을 초과또는 미만인것은 없애주는것


절대값 : tensor(10)
올림 : tensor(5.)
반올림 : tensor(4.)
내림 : tensor(4.)
클램프 tensor([[ 0.5000,  0.3000],
        [-0.5000,  0.4000]])


In [32]:
x = torch.randn(2,2)
y = torch.tensor([[1,2],
                  [3,4]])
print("최소값 :", torch.min(x))
print("최대값 :", torch.max(x))
print("평균 :", torch.mean(x))
print("표준편차 :", torch.std(x))
print("모든 원소의 합 :", torch.sum(x))
print("모든 원소의 합 :", torch.sum(y,dim=0))#dim=0:같은열더함 dim=1:같은 행 더함
print("모든 원소의 곱 :", torch.prod(y))
print("중복된 값 제거 :", torch.unique(torch.tensor([1,1,2,2,2,3,3,3,4,4,4])))

최소값 : tensor(0.4215)
최대값 : tensor(1.1482)
평균 : tensor(0.7436)
표준편차 : tensor(0.3583)
모든 원소의 합 : tensor(2.9742)
모든 원소의 합 : tensor([4, 6])
모든 원소의 곱 : tensor(24)
중복된 값 제거 : tensor([1, 2, 3, 4])


### 2-3. 내적(dot product)

In [36]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])

result = torch.matmul(x,y)
print(result)

tensor([[19, 22],
        [43, 50]])
