## 02. 텐서의 연산

In [1]:
import torch

### 2-1. 산술 연산

In [18]:
tensor = torch.rand(2,2)
print(tensor)

tensor = tensor * 2
print(tensor)

tensor = tensor + 1
print(tensor)



tensor([[0.4845, 0.1688],
        [0.0951, 0.0998]])
tensor([[0.9690, 0.3376],
        [0.1902, 0.1995]])
tensor([[1.9690, 1.3376],
        [1.1902, 1.1995]])


In [27]:
# 여러개의 텐서를 연산
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y) 

# print(x)
# print(y)
# print(x+y)
# print(add)
print(x,y)

# in-place 바꿔치기 연산
add = torch.add(x,y)
print(add)
y.add_(x) #앞에있는 값에 덮어 씌움
print(y)

tensor([[0.2336, 0.0515],
        [0.2707, 0.3133]]) tensor([[0.8622, 0.3658],
        [0.8913, 0.0134]])
tensor([[1.0958, 0.4172],
        [1.1621, 0.3268]])
tensor([[1.0958, 0.4172],
        [1.1621, 0.3268]])


In [33]:
# 빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x-y)
print(sub) 

tensor([[ 0.0059,  0.5050],
        [ 0.6340, -0.2019]])
tensor([[ 0.0059,  0.5050],
        [ 0.6340, -0.2019]])


In [35]:
# 곱하기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x*y)
print(mul) 

tensor([[0.0437, 0.1617],
        [0.1624, 0.2783]])
tensor([[0.0437, 0.1617],
        [0.1624, 0.2783]])


In [37]:
# 나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x,y)
print(x/y)
print(div) 

tensor([[1.0163, 1.2845],
        [3.8754, 2.0435]])
tensor([[1.0163, 1.2845],
        [3.8754, 2.0435]])
