## 03. Tensor의 조작

### 3-1. 인덱싱, 슬라이싱
- numpy처럼 활용 하면 됨

In [1]:
import torch

In [14]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1])
print(tensor[0,:])

a = torch.tensor([1,2,3,4,5])
print(a[-1])
print(a[-2:])

b = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
c = b[b > 5] # 조건부 인덱싱
d = b[b % 2 == 0]
e = b[[0,1],[1,2]]#특정 배열의 값을 넣어서 인덱싱 할 수 있다.
e

tensor(2)
tensor([1, 2])
tensor(5)
tensor([4, 5])


tensor([2, 6])

### 3-2. 텐서의 크기, 모양 변경

In [34]:
t = torch.rand(4,5)
print(t)

x = t.view(5,4) #같은 형태로 값을 변경해야함
print(x)

y = t.view(10,-1) # -1쓰면 자동으로 나눠줌
print(y)

tensor([[0.1916, 0.0511, 0.4924, 0.9549, 0.8586],
        [0.8355, 0.0684, 0.6007, 0.5625, 0.6473],
        [0.7449, 0.2723, 0.0314, 0.7557, 0.7782],
        [0.3717, 0.8858, 0.0481, 0.3557, 0.3034]])
tensor([[0.1916, 0.0511, 0.4924, 0.9549],
        [0.8586, 0.8355, 0.0684, 0.6007],
        [0.5625, 0.6473, 0.7449, 0.2723],
        [0.0314, 0.7557, 0.7782, 0.3717],
        [0.8858, 0.0481, 0.3557, 0.3034]])
tensor([[0.1916, 0.0511],
        [0.4924, 0.9549],
        [0.8586, 0.8355],
        [0.0684, 0.6007],
        [0.5625, 0.6473],
        [0.7449, 0.2723],
        [0.0314, 0.7557],
        [0.7782, 0.3717],
        [0.8858, 0.0481],
        [0.3557, 0.3034]])


### 3-3. Tensor의 숫자값 얻기 (스칼라에 대해서만 가능)

In [38]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y)
print(y.item())

10
tensor([0.7241])
0.7240814566612244


### 3-4. 차원 축소와 증가

#### 3-4-1. 차원축소
- 'torch.squeeze()' : 크기가 1인 차원을 축소함(없앰)

In [43]:
t = torch.rand(1,3,3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.1302, 0.7117, 0.4180],
         [0.9449, 0.0938, 0.5024],
         [0.1755, 0.6744, 0.5591]]])
torch.Size([1, 3, 3])
tensor([[0.1302, 0.7117, 0.4180],
        [0.9449, 0.0938, 0.5024],
        [0.1755, 0.6744, 0.5591]])
torch.Size([3, 3])


#### 3-4-2. 차원 증가(생성)
- 'torch.unsqueeze()' : 지정한 위치에 새로운 차원을 생성

In [53]:
t = torch.rand(3,3,3)
print(t)
print(t.shape)

ts = torch.unsqueeze(t, 1)
print(ts)
print(ts.shape)

tensor([[[0.9184, 0.8339, 0.4877],
         [0.5400, 0.9430, 0.9602],
         [0.3666, 0.5863, 0.2468]],

        [[0.5857, 0.5558, 0.5418],
         [0.2544, 0.6326, 0.2425],
         [0.8322, 0.6271, 0.7738]],

        [[0.9658, 0.2509, 0.7947],
         [0.6656, 0.3490, 0.8229],
         [0.9727, 0.8285, 0.2877]]])
torch.Size([3, 3, 3])
tensor([[[[0.9184, 0.8339, 0.4877],
          [0.5400, 0.9430, 0.9602],
          [0.3666, 0.5863, 0.2468]]],


        [[[0.5857, 0.5558, 0.5418],
          [0.2544, 0.6326, 0.2425],
          [0.8322, 0.6271, 0.7738]]],


        [[[0.9658, 0.2509, 0.7947],
          [0.6656, 0.3490, 0.8229],
          [0.9727, 0.8285, 0.2877]]]])
torch.Size([3, 1, 3, 3])


### 3-5. 텐서간 결합
- 'torch.stack()' : 동일한 형식의 두개의 텐서를 새롭게 그룹화(하나로)함
    - 새로운 차원이 생성

In [56]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])
z = torch.stack([x,y])
print(z)
print(z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- 'torch.cat()' : 하나의 텐서로 병합
    - 새로운 차원 생성 X
    - cat은 형태(행의 원소의 갯수는 같고)가 같지 않아도 괜찮다. dim = 0일때

In [64]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8],]) 
z = torch.cat((x,y), dim = 0)
print(z)
print(z.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


### 3-6. 텐서 나누기
- 'torch.chunck()' : 
    - 텐서를 몇개로 나눌지 지정해서 나누는 것
    - 나누어 떨어지지 않으면 마지막 조각은 크기가 다를 수 있음

In [73]:
t = torch.rand(5,3)
print(t)

a,b,c = torch.chunk(t,3, dim = 0) #튜플형태로 받아옴
print(a)
print(b)
print(c)

tensor([[0.4159, 0.8186, 0.2231],
        [0.4743, 0.9898, 0.2297],
        [0.7434, 0.8217, 0.6189],
        [0.8123, 0.2355, 0.8227],
        [0.7949, 0.1302, 0.2770]])
tensor([[0.4159, 0.8186, 0.2231],
        [0.4743, 0.9898, 0.2297]])
tensor([[0.7434, 0.8217, 0.6189],
        [0.8123, 0.2355, 0.8227]])
tensor([[0.7949, 0.1302, 0.2770]])


- 'torch.split()'
    - 텐서의 크기를 기준으로 나눔

In [89]:
t = torch.rand(3,6)
print(t)

x , y= torch.split(t,3,dim = 1)
print(x)
print(y)

tensor([[0.7649, 0.6059, 0.0902, 0.7992, 0.9653, 0.8624],
        [0.8228, 0.9554, 0.5664, 0.2754, 0.5078, 0.0889],
        [0.5753, 0.7522, 0.5603, 0.1711, 0.4898, 0.3355]])
tensor([[0.7649, 0.6059, 0.0902],
        [0.8228, 0.9554, 0.5664],
        [0.5753, 0.7522, 0.5603]])
tensor([[0.7992, 0.9653, 0.8624],
        [0.2754, 0.5078, 0.0889],
        [0.1711, 0.4898, 0.3355]])


In [91]:
t = torch.tensor([1,2,3,4,5])
print(t)

x , y , z= torch.split(t,[2,2,1],dim = 0)
print(x)
print(y)
print(z)

tensor([1, 2, 3, 4, 5])
tensor([1, 2])
tensor([3, 4])
tensor([5])
