## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [49]:
import torch
a = torch.tensor([2,4,6])
b = a+5
c = a-3
print(a)
print("5더한 :",b)
print("3 뺀 :",c)

tensor([2, 4, 6])
5더한 : tensor([ 7,  9, 11])
3 뺀 : tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [50]:
a = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
b = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

ans_1 = torch.add(a,b)
ans_2 = torch.sub(a,b)
ans_3 = torch.mul(a,b)
ans_4 = torch.div(a,b)

print("덧셈 :",a+b)
print("뺄셈 :",a-b)
print("곱셈 :",a*b)
print("나눗셈 :",a/b)

덧셈 : tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
뺄셈 : tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
곱셈 : tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
나눗셈 : tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [32]:
a = torch.tensor([[1,2,3], 
                  [4,5,6]])
b = torch.tensor([[7,8],
                  [9,10],
                  [11,12]])

R = torch.matmul(a,b)
print(R)

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [51]:
R = torch.tensor([[58,64],
                  [139,154]])
R = R+10

print(R)
print("클램프",torch.clamp(R, max=100))


tensor([[ 68,  74],
        [149, 164]])
클램프 tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [53]:
M = torch.tensor(    [[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

answer = torch.sum(M,dim=0)
print('각 열의 합계 :', answer)

각 열의 합계 : tensor([55, 60, 65, 70, 75])
