## PyTorch Quiz 1 : Tensor 초기화

In [2]:
import torch
import numpy as np

torch.__version__

'2.5.1'

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [2]:
tensor = torch.empty(3,4)
print(tensor)

tensor([[ 2.8026e-45,  0.0000e+00, -1.8460e-09,  3.2953e-41],
        [-1.8460e-09,  3.2953e-41, -1.8460e-09,  3.2953e-41],
        [ 2.8026e-44,  4.4480e-41, -4.4673e+04,  4.4480e-41]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [3]:
tensor = torch.zeros(2,5,3, dtype=torch.float64)
print(tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [4]:
tensor = torch.ones(4,4, dtype=torch.int)
print(tensor)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [5]:
tensor = torch.rand(3,3)
print(tensor)

tensor([[0.8427, 0.0808, 0.3842],
        [0.6249, 0.7828, 0.4491],
        [0.0592, 0.8254, 0.7511]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [8]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요.

In [8]:
tensor = torch.randn(2,2)
print(tensor)
new_tensor = torch.zeros_like(tensor)
print(new_tensor)

tensor([[-0.0276,  0.9387],
        [-1.2765,  0.4373]])
tensor([[0., 0.],
        [0., 0.]])
